name: myportfolioworkflow

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag version
        id: extract_tag
        run: |
          VERSION="${GITHUB_REF##*/}"
          VERSION="${VERSION#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Echo build message
        run: echo "Building Image and Pushing to Docker"

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: myportfolio:latest,myportfolio:${{ steps.extract_tag.outputs.version }}
